"""update message foreign key in attachment table

Revision ID: 0a425e1877bc
Revises: a1e364a7c401
Create Date: 2025-10-13 11:34:04.478553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a425e1877bc'
down_revision: Union[str, Sequence[str], None] = 'a1e364a7c401'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('attachment_message_id_fkey'), 'attachment', type_='foreignkey')
    op.create_foreign_key(None, 'attachment', 'message', ['message_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attachment', type_='foreignkey')
    op.create_foreign_key(op.f('attachment_message_id_fkey'), 'attachment', 'message', ['message_id'], ['id'])
    # ### end Alembic commands ###
